import { RESTAURANT_IMAGE } from "@/lib/constants";

export interface RestaurantType {
  id: string;
  name: string;
  image: string;
  costForTwo: string;
  distance: string;
  address: string;
  offer: string;
}

export const restaurantsList: RestaurantType[] = [
  {
    id: "res-101",
    name: "Zahra Biryani House",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹300 for two",
    distance: "1.3 km",
    address: "Jama Masjid, Old Delhi",
    offer: "WALK-IN 20% OFF",
  },
  {
    id: "res-102",
    name: "Spice Route Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹450 for two",
    distance: "2.1 km",
    address: "Karol Bagh, Delhi",
    offer: "10% OFF with HDFC Bank",
  },
  {
    id: "res-103",
    name: "Royal Mughlai Darbar",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "3.4 km",
    address: "Chandni Chowk, Delhi",
    offer: "Flat ₹100 OFF",
  },
  {
    id: "res-104",
    name: "Urban Tandoor",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹600 for two",
    distance: "1.8 km",
    address: "Rajouri Garden, Delhi",
    offer: "20% OFF up to ₹120",
  },
  {
    id: "res-105",
    name: "Delhi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹350 for two",
    distance: "0.9 km",
    address: "Lajpat Nagar, Delhi",
    offer: "15% OFF with ICICI Cards",
  },
  {
    id: "res-106",
    name: "The Biryani Club",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹400 for two",
    distance: "2.7 km",
    address: "Saket, Delhi",
    offer: "BUY 1 GET 1",
  },
  {
    id: "res-107",
    name: "Masala Junction",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹280 for two",
    distance: "1.1 km",
    address: "Dwarka, Delhi",
    offer: "Flat 25% OFF",
  },
  {
    id: "res-108",
    name: "Nawab’s Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹550 for two",
    distance: "4.2 km",
    address: "Civil Lines, Delhi",
    offer: "10% OFF with SBI Cards",
  },
  {
    id: "res-109",
    name: "Tandoori Tales",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹480 for two",
    distance: "2.9 km",
    address: "Pitampura, Delhi",
    offer: "₹75 OFF above ₹399",
  },
  {
    id: "res-110",
    name: "House of Kebabs",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹650 for two",
    distance: "5.1 km",
    address: "Connaught Place, Delhi",
    offer: "20% OFF with Axis Bank",
  },
  {
    id: "res-111",
    name: "Biryani & Beyond",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹420 for two",
    distance: "3.0 km",
    address: "Mayur Vihar, Delhi",
    offer: "Flat ₹125 OFF",
  },
  {
    id: "res-112",
    name: "Desi Handi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹320 for two",
    distance: "1.5 km",
    address: "Preet Vihar, Delhi",
    offer: "WALK-IN 15% OFF",
  },
  {
    id: "res-113",
    name: "The Spice Affair",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹700 for two",
    distance: "6.0 km",
    address: "Vasant Kunj, Delhi",
    offer: "10% OFF on Weekdays",
  },
  {
    id: "res-114",
    name: "Lucknowi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "2.4 km",
    address: "Shaheen Bagh, Delhi",
    offer: "Flat ₹150 OFF",
  },
  {
    id: "res-115",
    name: "Khaati Peeti Rasoi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹260 for two",
    distance: "0.7 km",
    address: "Uttam Nagar, Delhi",
    offer: "20% OFF on Combos",
  },
  {
    id: "res-116",
    name: "Flavours of India",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹580 for two",
    distance: "4.8 km",
    address: "Green Park, Delhi",
    offer: "₹100 Cashback",
  },
  {
    id: "res-117",
    name: "Street Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹220 for two",
    distance: "1.0 km",
    address: "Ashok Vihar, Delhi",
    offer: "Flat 30% OFF",
  },
  {
    id: "res-118",
    name: "Dum Pukht Express",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹750 for two",
    distance: "6.5 km",
    address: "Aerocity, Delhi",
    offer: "10% OFF with Amex",
  },
  {
    id: "res-119",
    name: "Curry & Claypot",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹360 for two",
    distance: "2.2 km",
    address: "Rohini, Delhi",
    offer: "₹80 OFF above ₹299",
  },
  {
    id: "res-120",
    name: "Mehfil-e-Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹520 for two",
    distance: "3.9 km",
    address: "Okhla, Delhi",
    offer: "20% OFF up to ₹150",
  },
  {
    id: "res-1065741",
    name: "Zahra Biryani House",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹300 for two",
    distance: "1.3 km",
    address: "Jama Masjid, Old Delhi",
    offer: "WALK-IN 20% OFF",
  },
  {
    id: "res-1065742",
    name: "Spice Route Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹450 for two",
    distance: "2.1 km",
    address: "Karol Bagh, Delhi",
    offer: "10% OFF with HDFC Bank",
  },
  {
    id: "res-1065743",
    name: "Royal Mughlai Darbar",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "3.4 km",
    address: "Chandni Chowk, Delhi",
    offer: "Flat ₹100 OFF",
  },
  {
    id: "res-1065744",
    name: "Urban Tandoor",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹600 for two",
    distance: "1.8 km",
    address: "Rajouri Garden, Delhi",
    offer: "20% OFF up to ₹120",
  },
  {
    id: "res-1065745",
    name: "Delhi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹350 for two",
    distance: "0.9 km",
    address: "Lajpat Nagar, Delhi",
    offer: "15% OFF with ICICI Cards",
  },
  {
    id: "res-1065746",
    name: "The Biryani Club",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹400 for two",
    distance: "2.7 km",
    address: "Saket, Delhi",
    offer: "BUY 1 GET 1",
  },
  {
    id: "res-1065747",
    name: "Masala Junction",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹280 for two",
    distance: "1.1 km",
    address: "Dwarka, Delhi",
    offer: "Flat 25% OFF",
  },
  {
    id: "res-1065748",
    name: "Nawab’s Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹550 for two",
    distance: "4.2 km",
    address: "Civil Lines, Delhi",
    offer: "10% OFF with SBI Cards",
  },
  {
    id: "res-1065749",
    name: "Tandoori Tales",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹480 for two",
    distance: "2.9 km",
    address: "Pitampura, Delhi",
    offer: "₹75 OFF above ₹399",
  },
  {
    id: "res-1165740",
    name: "House of Kebabs",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹650 for two",
    distance: "5.1 km",
    address: "Connaught Place, Delhi",
    offer: "20% OFF with Axis Bank",
  },
  {
    id: "res-1165741",
    name: "Biryani & Beyond",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹420 for two",
    distance: "3.0 km",
    address: "Mayur Vihar, Delhi",
    offer: "Flat ₹125 OFF",
  },
  {
    id: "res-1165742",
    name: "Desi Handi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹320 for two",
    distance: "1.5 km",
    address: "Preet Vihar, Delhi",
    offer: "WALK-IN 15% OFF",
  },
  {
    id: "res-1165743",
    name: "The Spice Affair",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹700 for two",
    distance: "6.0 km",
    address: "Vasant Kunj, Delhi",
    offer: "10% OFF on Weekdays",
  },
  {
    id: "res-1165744",
    name: "Lucknowi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "2.4 km",
    address: "Shaheen Bagh, Delhi",
    offer: "Flat ₹150 OFF",
  },
  {
    id: "res-1165745",
    name: "Khaati Peeti Rasoi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹260 for two",
    distance: "0.7 km",
    address: "Uttam Nagar, Delhi",
    offer: "20% OFF on Combos",
  },
  {
    id: "res-1165746",
    name: "Flavours of India",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹580 for two",
    distance: "4.8 km",
    address: "Green Park, Delhi",
    offer: "₹100 Cashback",
  },
  {
    id: "res-1165747",
    name: "Street Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹220 for two",
    distance: "1.0 km",
    address: "Ashok Vihar, Delhi",
    offer: "Flat 30% OFF",
  },
  {
    id: "res-1165748",
    name: "Dum Pukht Express",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹750 for two",
    distance: "6.5 km",
    address: "Aerocity, Delhi",
    offer: "10% OFF with Amex",
  },
  {
    id: "res-1165749",
    name: "Curry & Claypot",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹360 for two",
    distance: "2.2 km",
    address: "Rohini, Delhi",
    offer: "₹80 OFF above ₹299",
  },
  {
    id: "res-1265740",
    name: "Mehfil-e-Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹520 for two",
    distance: "3.9 km",
    address: "Okhla, Delhi",
    offer: "20% OFF up to ₹150",
  },
  {
    id: "res-45101",
    name: "Zahra Biryani House",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹300 for two",
    distance: "1.3 km",
    address: "Jama Masjid, Old Delhi",
    offer: "WALK-IN 20% OFF",
  },
  {
    id: "res-45102",
    name: "Spice Route Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹450 for two",
    distance: "2.1 km",
    address: "Karol Bagh, Delhi",
    offer: "10% OFF with HDFC Bank",
  },
  {
    id: "res-45103",
    name: "Royal Mughlai Darbar",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "3.4 km",
    address: "Chandni Chowk, Delhi",
    offer: "Flat ₹100 OFF",
  },
  {
    id: "res-45104",
    name: "Urban Tandoor",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹600 for two",
    distance: "1.8 km",
    address: "Rajouri Garden, Delhi",
    offer: "20% OFF up to ₹120",
  },
  {
    id: "res-45105",
    name: "Delhi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹350 for two",
    distance: "0.9 km",
    address: "Lajpat Nagar, Delhi",
    offer: "15% OFF with ICICI Cards",
  },
  {
    id: "res-45106",
    name: "The Biryani Club",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹400 for two",
    distance: "2.7 km",
    address: "Saket, Delhi",
    offer: "BUY 1 GET 1",
  },
  {
    id: "res-45107",
    name: "Masala Junction",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹280 for two",
    distance: "1.1 km",
    address: "Dwarka, Delhi",
    offer: "Flat 25% OFF",
  },
  {
    id: "res-45108",
    name: "Nawab’s Kitchen",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹550 for two",
    distance: "4.2 km",
    address: "Civil Lines, Delhi",
    offer: "10% OFF with SBI Cards",
  },
  {
    id: "res-45109",
    name: "Tandoori Tales",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹480 for two",
    distance: "2.9 km",
    address: "Pitampura, Delhi",
    offer: "₹75 OFF above ₹399",
  },
  {
    id: "res-45110",
    name: "House of Kebabs",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹650 for two",
    distance: "5.1 km",
    address: "Connaught Place, Delhi",
    offer: "20% OFF with Axis Bank",
  },
  {
    id: "res-45111",
    name: "Biryani & Beyond",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹420 for two",
    distance: "3.0 km",
    address: "Mayur Vihar, Delhi",
    offer: "Flat ₹125 OFF",
  },
  {
    id: "res-45112",
    name: "Desi Handi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹320 for two",
    distance: "1.5 km",
    address: "Preet Vihar, Delhi",
    offer: "WALK-IN 15% OFF",
  },
  {
    id: "res-45113",
    name: "The Spice Affair",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹700 for two",
    distance: "6.0 km",
    address: "Vasant Kunj, Delhi",
    offer: "10% OFF on Weekdays",
  },
  {
    id: "res-45114",
    name: "Lucknowi Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹500 for two",
    distance: "2.4 km",
    address: "Shaheen Bagh, Delhi",
    offer: "Flat ₹150 OFF",
  },
  {
    id: "res-45115",
    name: "Khaati Peeti Rasoi",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹260 for two",
    distance: "0.7 km",
    address: "Uttam Nagar, Delhi",
    offer: "20% OFF on Combos",
  },
  {
    id: "res-45116",
    name: "Flavours of India",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹580 for two",
    distance: "4.8 km",
    address: "Green Park, Delhi",
    offer: "₹100 Cashback",
  },
  {
    id: "res-45117",
    name: "Street Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹220 for two",
    distance: "1.0 km",
    address: "Ashok Vihar, Delhi",
    offer: "Flat 30% OFF",
  },
  {
    id: "res-45118",
    name: "Dum Pukht Express",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹750 for two",
    distance: "6.5 km",
    address: "Aerocity, Delhi",
    offer: "10% OFF with Amex",
  },
  {
    id: "res-45119",
    name: "Curry & Claypot",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹360 for two",
    distance: "2.2 km",
    address: "Rohini, Delhi",
    offer: "₹80 OFF above ₹299",
  },
  {
    id: "res-45120",
    name: "Mehfil-e-Zaika",
    image: RESTAURANT_IMAGE,
    costForTwo: "₹520 for two",
    distance: "3.9 km",
    address: "Okhla, Delhi",
    offer: "20% OFF up to ₹150",
  },
];

export const restaurantsById: Record<string, RestaurantType> =
  restaurantsList.reduce(
    (acc, restaurant) => {
      acc[restaurant.id] = restaurant;
      return acc;
    },
    {} as Record<string, RestaurantType>,
  );

export interface BlinkitProductType {
  id: string;
  name: string;
  image: string;
  price: number;
  time: string;
  offer?: string;
}
export const blinkitProducts: BlinkitProductType[] = [
  // --- Original Items ---
  {
    id: "milk-amul-500",
    name: "Amul Toned Milk 500ml",
    image:
      "https://imgs.search.brave.com/HIDsdrp71Mek4EB-F8x71hx5H19JPV36LHyD1jiBrkw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/emVwdG9ub3cuY29t/L3Byb2R1Y3Rpb24v/dHI6dy00MDMsYXIt/MTIwMC0xMjAwLHBy/LXRydWUsZi1hdXRv/LHEtNDAsZHByLTIv/Y21zL3Byb2R1Y3Rf/dmFyaWFudC8zYThk/NDExMy05MzlkLTRl/NGUtYTdjZS05NmU1/MjE1MmJhOTcuanBl/Zw",
    price: 28,
    time: "8 mins",
  },
  {
    id: "bread-britannia",
    name: "Britannia Brown Bread",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600",
    price: 45,
    time: "9 mins",
    offer: "₹10 OFF",
  },
  {
    id: "egg-farm-12",
    name: "Farm Fresh Eggs (12 pcs)",
    image: "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600",
    price: 78,
    time: "10 mins",
  },
  {
    id: "apple-kashmir",
    name: "Kashmiri Apples (1kg)",
    image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600",
    price: 149,
    time: "12 mins",
    offer: "15% OFF",
  },
  {
    id: "tomato-hybrid",
    name: "Hybrid Tomatoes (1kg)",
    image:
      "https://imgs.search.brave.com/uWO3yrFqlscFBaSTXrrLtc5TORvJddKDQNqasga-BWo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/cHJvZC53ZWJzaXRl/LWZpbGVzLmNvbS82/M2VkMDg0ODRjMDY5/ZDA0OTJmNWIwYmMv/NjU0MTUyNDJlZWQ1/MTZkZGQwODIxNTll/X0hlcm9JbWFnZV9U/b21hdG8ud2VicA",
    price: 36,
    time: "8 mins",
  },
  {
    id: "atta-ashirvaad",
    name: "Aashirvaad Atta 5kg",
    image:
      "https://imgs.search.brave.com/EBkzq7KL2DYnRN5HPqo_Dx1Le3Et5f6th46E0QlLE_M/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c3RhcnF1aWsuY29t/L2Nkbi9zaG9wL2Zp/bGVzL1NRMTAwMjc1/X2FkOGY4MmRhLThh/MmYtNGU5Zi1iZTA1/LTlmYTc3MjU2OWFh/Mi5qcGc_dj0xNzUx/MjEwOTc4JndpZHRo/PTUzMw",
    price: 279,
    time: "14 mins",
    offer: "₹30 OFF",
  },
  {
    id: "oil-fortune-1l",
    name: "Fortune Sunflower Oil 1L",
    image:
      "https://imgs.search.brave.com/wpL3Jnukh80T80WlCQKUkP_TZNOM2iZolbpE6AeFG3E/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/ZnJlZS1waG90by9w/bmctc3VuZmxvd2Vy/cy1vaWwtcGxhc3Rp/Yy1ib3R0bGUtZ2xh/c3MtamFycy1pc29s/YXRlZC13aGl0ZS1i/YWNrZ3JvdW5kXzE4/NTE5My0xNjQyNjYu/anBnP3NlbXQ9YWlz/X2h5YnJpZCZ3PTc0/MA",
    price: 149,
    time: "11 mins",
  },
  {
    id: "chips-lays-magic",
    name: "Lays Magic Masala",
    image: "https://images.unsplash.com/photo-1613919113640-25732ec5e61f?w=600",
    price: 20,
    time: "7 mins",
  },

  // --- New Items Added Below ---
  {
    id: "coke-750",
    name: "Coca Cola Soft Drink 750ml",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600",
    price: 40,
    time: "8 mins",
    offer: "Buy 2 Get 1",
  },
  {
    id: "maggi-single",
    name: "Maggi Masala Noodles",
    image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600",
    price: 14,
    time: "5 mins",
  },
  {
    id: "onion-1kg",
    name: "Fresh Onion 1kg",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600",
    price: 35,
    time: "12 mins",
  },
  {
    id: "butter-amul-100",
    name: "Amul Butter 100g",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600",
    price: 58,
    time: "7 mins",
  },
  {
    id: "chocolate-dairy-milk",
    name: "Cadbury Dairy Milk Silk",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600",
    price: 80,
    time: "6 mins",
    offer: "10% OFF",
  },
  {
    id: "banana-robusta",
    name: "Robusta Banana (6 pcs)",
    image:
      "https://imgs.search.brave.com/SPn0NejqqX6JQx9xtoW8rmnvS6ZkTYmTD4UlBNc5FGE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/emVwdG9ub3cuY29t/L3Byb2R1Y3Rpb24v/aWstc2VvL3RyOnct/NDcwLGFyLTMwMDAt/MzAwMCxwci10cnVl/LGYtYXV0byxxLTQw/LGRwci0yL2Ntcy9w/cm9kdWN0X3Zhcmlh/bnQvNDdkZmJjYWEt/ZDczYi00ODViLWI1/NjctOWRkYzBkY2Y5/NDcwL0JhbmFuYS1S/b2J1c3RhLmpwZWc",
    price: 40,
    time: "10 mins",
  },
  {
    id: "paneer-fresh",
    name: "Fresh Malai Paneer 200g",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600",
    price: 95,
    time: "9 mins",
  },
  {
    id: "detergent-surf",
    name: "Surf Excel Matic Liquid 1L",
    image: "https://imgs.search.brave.com/F-mlZiMwaDxY7uuT_8bSos3gC5SNydmuUKQ1xLw7aq0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFKMGFzLXgtdEwu/anBn",
    price: 220,
    time: "15 mins",
    offer: "₹50 OFF",
  },
];

export const blinkitItemsById: Record<string, BlinkitProductType> =
  blinkitProducts.reduce(
    (acc, prod) => {
      acc[prod.id] = prod;
      return acc;
    },
    {} as Record<string, BlinkitProductType>,
  );

export async function getAwaitedBlinkitData(): Promise<BlinkitProductType[]> {
  await new Promise((res, rej) => {
    setTimeout(() => res("success"), 2000);
  });
  return blinkitProducts;
}
