import { RESTAURANT_IMAGE } from "@/lib/constants";

export interface RestaurantType {
    id: string;
    name: string;
    image: string;
    costForTwo: string;
    distance: string;
    address: string;
    offer: string;
}

export const restaurantsList: RestaurantType[] = [
    {
        id: "res-101",
        name: "Zahra Biryani House",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹300 for two",
        distance: "1.3 km",
        address: "Jama Masjid, Old Delhi",
        offer: "WALK-IN 20% OFF",
    },
    {
        id: "res-102",
        name: "Spice Route Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹450 for two",
        distance: "2.1 km",
        address: "Karol Bagh, Delhi",
        offer: "10% OFF with HDFC Bank",
    },
    {
        id: "res-103",
        name: "Royal Mughlai Darbar",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "3.4 km",
        address: "Chandni Chowk, Delhi",
        offer: "Flat ₹100 OFF",
    },
    {
        id: "res-104",
        name: "Urban Tandoor",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹600 for two",
        distance: "1.8 km",
        address: "Rajouri Garden, Delhi",
        offer: "20% OFF up to ₹120",
    },
    {
        id: "res-105",
        name: "Delhi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹350 for two",
        distance: "0.9 km",
        address: "Lajpat Nagar, Delhi",
        offer: "15% OFF with ICICI Cards",
    },
    {
        id: "res-106",
        name: "The Biryani Club",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹400 for two",
        distance: "2.7 km",
        address: "Saket, Delhi",
        offer: "BUY 1 GET 1",
    },
    {
        id: "res-107",
        name: "Masala Junction",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹280 for two",
        distance: "1.1 km",
        address: "Dwarka, Delhi",
        offer: "Flat 25% OFF",
    },
    {
        id: "res-108",
        name: "Nawab’s Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹550 for two",
        distance: "4.2 km",
        address: "Civil Lines, Delhi",
        offer: "10% OFF with SBI Cards",
    },
    {
        id: "res-109",
        name: "Tandoori Tales",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹480 for two",
        distance: "2.9 km",
        address: "Pitampura, Delhi",
        offer: "₹75 OFF above ₹399",
    },
    {
        id: "res-110",
        name: "House of Kebabs",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹650 for two",
        distance: "5.1 km",
        address: "Connaught Place, Delhi",
        offer: "20% OFF with Axis Bank",
    },
    {
        id: "res-111",
        name: "Biryani & Beyond",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹420 for two",
        distance: "3.0 km",
        address: "Mayur Vihar, Delhi",
        offer: "Flat ₹125 OFF",
    },
    {
        id: "res-112",
        name: "Desi Handi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹320 for two",
        distance: "1.5 km",
        address: "Preet Vihar, Delhi",
        offer: "WALK-IN 15% OFF",
    },
    {
        id: "res-113",
        name: "The Spice Affair",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹700 for two",
        distance: "6.0 km",
        address: "Vasant Kunj, Delhi",
        offer: "10% OFF on Weekdays",
    },
    {
        id: "res-114",
        name: "Lucknowi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "2.4 km",
        address: "Shaheen Bagh, Delhi",
        offer: "Flat ₹150 OFF",
    },
    {
        id: "res-115",
        name: "Khaati Peeti Rasoi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹260 for two",
        distance: "0.7 km",
        address: "Uttam Nagar, Delhi",
        offer: "20% OFF on Combos",
    },
    {
        id: "res-116",
        name: "Flavours of India",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹580 for two",
        distance: "4.8 km",
        address: "Green Park, Delhi",
        offer: "₹100 Cashback",
    },
    {
        id: "res-117",
        name: "Street Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹220 for two",
        distance: "1.0 km",
        address: "Ashok Vihar, Delhi",
        offer: "Flat 30% OFF",
    },
    {
        id: "res-118",
        name: "Dum Pukht Express",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹750 for two",
        distance: "6.5 km",
        address: "Aerocity, Delhi",
        offer: "10% OFF with Amex",
    },
    {
        id: "res-119",
        name: "Curry & Claypot",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹360 for two",
        distance: "2.2 km",
        address: "Rohini, Delhi",
        offer: "₹80 OFF above ₹299",
    },
    {
        id: "res-120",
        name: "Mehfil-e-Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹520 for two",
        distance: "3.9 km",
        address: "Okhla, Delhi",
        offer: "20% OFF up to ₹150",
    },
    {
        id: "res-1065741",
        name: "Zahra Biryani House",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹300 for two",
        distance: "1.3 km",
        address: "Jama Masjid, Old Delhi",
        offer: "WALK-IN 20% OFF",
    },
    {
        id: "res-1065742",
        name: "Spice Route Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹450 for two",
        distance: "2.1 km",
        address: "Karol Bagh, Delhi",
        offer: "10% OFF with HDFC Bank",
    },
    {
        id: "res-1065743",
        name: "Royal Mughlai Darbar",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "3.4 km",
        address: "Chandni Chowk, Delhi",
        offer: "Flat ₹100 OFF",
    },
    {
        id: "res-1065744",
        name: "Urban Tandoor",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹600 for two",
        distance: "1.8 km",
        address: "Rajouri Garden, Delhi",
        offer: "20% OFF up to ₹120",
    },
    {
        id: "res-1065745",
        name: "Delhi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹350 for two",
        distance: "0.9 km",
        address: "Lajpat Nagar, Delhi",
        offer: "15% OFF with ICICI Cards",
    },
    {
        id: "res-1065746",
        name: "The Biryani Club",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹400 for two",
        distance: "2.7 km",
        address: "Saket, Delhi",
        offer: "BUY 1 GET 1",
    },
    {
        id: "res-1065747",
        name: "Masala Junction",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹280 for two",
        distance: "1.1 km",
        address: "Dwarka, Delhi",
        offer: "Flat 25% OFF",
    },
    {
        id: "res-1065748",
        name: "Nawab’s Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹550 for two",
        distance: "4.2 km",
        address: "Civil Lines, Delhi",
        offer: "10% OFF with SBI Cards",
    },
    {
        id: "res-1065749",
        name: "Tandoori Tales",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹480 for two",
        distance: "2.9 km",
        address: "Pitampura, Delhi",
        offer: "₹75 OFF above ₹399",
    },
    {
        id: "res-1165740",
        name: "House of Kebabs",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹650 for two",
        distance: "5.1 km",
        address: "Connaught Place, Delhi",
        offer: "20% OFF with Axis Bank",
    },
    {
        id: "res-1165741",
        name: "Biryani & Beyond",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹420 for two",
        distance: "3.0 km",
        address: "Mayur Vihar, Delhi",
        offer: "Flat ₹125 OFF",
    },
    {
        id: "res-1165742",
        name: "Desi Handi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹320 for two",
        distance: "1.5 km",
        address: "Preet Vihar, Delhi",
        offer: "WALK-IN 15% OFF",
    },
    {
        id: "res-1165743",
        name: "The Spice Affair",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹700 for two",
        distance: "6.0 km",
        address: "Vasant Kunj, Delhi",
        offer: "10% OFF on Weekdays",
    },
    {
        id: "res-1165744",
        name: "Lucknowi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "2.4 km",
        address: "Shaheen Bagh, Delhi",
        offer: "Flat ₹150 OFF",
    },
    {
        id: "res-1165745",
        name: "Khaati Peeti Rasoi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹260 for two",
        distance: "0.7 km",
        address: "Uttam Nagar, Delhi",
        offer: "20% OFF on Combos",
    },
    {
        id: "res-1165746",
        name: "Flavours of India",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹580 for two",
        distance: "4.8 km",
        address: "Green Park, Delhi",
        offer: "₹100 Cashback",
    },
    {
        id: "res-1165747",
        name: "Street Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹220 for two",
        distance: "1.0 km",
        address: "Ashok Vihar, Delhi",
        offer: "Flat 30% OFF",
    },
    {
        id: "res-1165748",
        name: "Dum Pukht Express",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹750 for two",
        distance: "6.5 km",
        address: "Aerocity, Delhi",
        offer: "10% OFF with Amex",
    },
    {
        id: "res-1165749",
        name: "Curry & Claypot",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹360 for two",
        distance: "2.2 km",
        address: "Rohini, Delhi",
        offer: "₹80 OFF above ₹299",
    },
    {
        id: "res-1265740",
        name: "Mehfil-e-Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹520 for two",
        distance: "3.9 km",
        address: "Okhla, Delhi",
        offer: "20% OFF up to ₹150",
    },
    {
        id: "res-45101",
        name: "Zahra Biryani House",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹300 for two",
        distance: "1.3 km",
        address: "Jama Masjid, Old Delhi",
        offer: "WALK-IN 20% OFF",
    },
    {
        id: "res-45102",
        name: "Spice Route Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹450 for two",
        distance: "2.1 km",
        address: "Karol Bagh, Delhi",
        offer: "10% OFF with HDFC Bank",
    },
    {
        id: "res-45103",
        name: "Royal Mughlai Darbar",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "3.4 km",
        address: "Chandni Chowk, Delhi",
        offer: "Flat ₹100 OFF",
    },
    {
        id: "res-45104",
        name: "Urban Tandoor",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹600 for two",
        distance: "1.8 km",
        address: "Rajouri Garden, Delhi",
        offer: "20% OFF up to ₹120",
    },
    {
        id: "res-45105",
        name: "Delhi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹350 for two",
        distance: "0.9 km",
        address: "Lajpat Nagar, Delhi",
        offer: "15% OFF with ICICI Cards",
    },
    {
        id: "res-45106",
        name: "The Biryani Club",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹400 for two",
        distance: "2.7 km",
        address: "Saket, Delhi",
        offer: "BUY 1 GET 1",
    },
    {
        id: "res-45107",
        name: "Masala Junction",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹280 for two",
        distance: "1.1 km",
        address: "Dwarka, Delhi",
        offer: "Flat 25% OFF",
    },
    {
        id: "res-45108",
        name: "Nawab’s Kitchen",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹550 for two",
        distance: "4.2 km",
        address: "Civil Lines, Delhi",
        offer: "10% OFF with SBI Cards",
    },
    {
        id: "res-45109",
        name: "Tandoori Tales",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹480 for two",
        distance: "2.9 km",
        address: "Pitampura, Delhi",
        offer: "₹75 OFF above ₹399",
    },
    {
        id: "res-45110",
        name: "House of Kebabs",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹650 for two",
        distance: "5.1 km",
        address: "Connaught Place, Delhi",
        offer: "20% OFF with Axis Bank",
    },
    {
        id: "res-45111",
        name: "Biryani & Beyond",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹420 for two",
        distance: "3.0 km",
        address: "Mayur Vihar, Delhi",
        offer: "Flat ₹125 OFF",
    },
    {
        id: "res-45112",
        name: "Desi Handi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹320 for two",
        distance: "1.5 km",
        address: "Preet Vihar, Delhi",
        offer: "WALK-IN 15% OFF",
    },
    {
        id: "res-45113",
        name: "The Spice Affair",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹700 for two",
        distance: "6.0 km",
        address: "Vasant Kunj, Delhi",
        offer: "10% OFF on Weekdays",
    },
    {
        id: "res-45114",
        name: "Lucknowi Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹500 for two",
        distance: "2.4 km",
        address: "Shaheen Bagh, Delhi",
        offer: "Flat ₹150 OFF",
    },
    {
        id: "res-45115",
        name: "Khaati Peeti Rasoi",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹260 for two",
        distance: "0.7 km",
        address: "Uttam Nagar, Delhi",
        offer: "20% OFF on Combos",
    },
    {
        id: "res-45116",
        name: "Flavours of India",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹580 for two",
        distance: "4.8 km",
        address: "Green Park, Delhi",
        offer: "₹100 Cashback",
    },
    {
        id: "res-45117",
        name: "Street Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹220 for two",
        distance: "1.0 km",
        address: "Ashok Vihar, Delhi",
        offer: "Flat 30% OFF",
    },
    {
        id: "res-45118",
        name: "Dum Pukht Express",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹750 for two",
        distance: "6.5 km",
        address: "Aerocity, Delhi",
        offer: "10% OFF with Amex",
    },
    {
        id: "res-45119",
        name: "Curry & Claypot",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹360 for two",
        distance: "2.2 km",
        address: "Rohini, Delhi",
        offer: "₹80 OFF above ₹299",
    },
    {
        id: "res-45120",
        name: "Mehfil-e-Zaika",
        image: RESTAURANT_IMAGE,
        costForTwo: "₹520 for two",
        distance: "3.9 km",
        address: "Okhla, Delhi",
        offer: "20% OFF up to ₹150",
    },
];

export const restaurantsById: Record<string, RestaurantType> =
    restaurantsList.reduce((acc, restaurant) => {
        acc[restaurant.id] = restaurant
        return acc
    }, {} as Record<string, RestaurantType>)