import type { Metadata } from "next";
import Footer from "@/components/Footer/Footer";
import HeaderMinimal from "@/components/Header/HeaderMinimal";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderMinimal />
      {children}
      <Footer />
    </>
  );
}
