import type { Metadata } from "next";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/Footer";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {modal}
      {children}
      <Footer />
    </>
  );
}
